[package]
name="fouine-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
thiserror = "1.0.40"
log = "0.4.18"
env_logger = "0.10.0"
uuid = { version="1.3.3", features=["serde"] }
sqlx = { version="0.6.3", features=["uuid", "postgres", "runtime-actix-native-tls", "chrono"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
chrono = { vesion="0.4.26", features = ["serde"] }
async-trait = "0.1.68"

[dev-dependencies]
sqlx-cli = "0.6.3"