[package]
name="fouine-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
diesel = { version = "2.0.4", features = ["postgres", "r2d2"] }
thiserror = "1.0.40"
log = "0.4.18"
env_logger = "0.10.0"
uuid = "1.3.3"
r2d2 = "0.8.8"